#ifndef APP_CONFIG_TEMPLATE_H
#define APP_CONFIG_TEMPLATE_H

/* PROJECT CONFIGURATION */
#define PROJECT_NAME "My Embedded Project"
#define PROJECT_VERSION "1.0.0"
#define HARDWARE_PLATFORM "STM32F407"

/* STATE MACHINE TUNING */
#ifdef SM_TASK_PERIOD_MS
#undef SM_TASK_PERIOD_MS
#endif
#define SM_TASK_PERIOD_MS 10U

#ifdef SM_STATE_TIMEOUT_MS
#undef SM_STATE_TIMEOUT_MS
#endif
#define SM_STATE_TIMEOUT_MS 5000U

/* ERROR HANDLING TUNING */
#ifdef ERROR_MAX_RECOVERY_ATTEMPTS
#undef ERROR_MAX_RECOVERY_ATTEMPTS
#endif
#define ERROR_MAX_RECOVERY_ATTEMPTS 3U

#ifdef ERROR_MINOR_RETRY_COUNT
#undef ERROR_MINOR_RETRY_COUNT
#endif
#define ERROR_MINOR_RETRY_COUNT 3U

#ifdef ERROR_MINOR_TIMEOUT_MS
#undef ERROR_MINOR_TIMEOUT_MS
#endif
#define ERROR_MINOR_TIMEOUT_MS 50U

#ifdef ERROR_HISTORY_SIZE
#undef ERROR_HISTORY_SIZE
#endif
#define ERROR_HISTORY_SIZE 16U

/* DEBUG SYSTEM CONFIGURATION */
#ifdef DEBUG_ENABLE_INIT_MESSAGES
#undef DEBUG_ENABLE_INIT_MESSAGES
#endif
#define DEBUG_ENABLE_INIT_MESSAGES 1U

#ifdef DEBUG_ENABLE_RUNTIME_MESSAGES
#undef DEBUG_ENABLE_RUNTIME_MESSAGES
#endif
#define DEBUG_ENABLE_RUNTIME_MESSAGES 1U

#ifdef DEBUG_ENABLE_PERIODIC_MESSAGES
#undef DEBUG_ENABLE_PERIODIC_MESSAGES
#endif
#define DEBUG_ENABLE_PERIODIC_MESSAGES 1U

#ifdef DEBUG_PERIODIC_INTERVAL_MS
#undef DEBUG_PERIODIC_INTERVAL_MS
#endif
#define DEBUG_PERIODIC_INTERVAL_MS 1000U

#ifdef DEBUG_MAX_MESSAGE_LENGTH
#undef DEBUG_MAX_MESSAGE_LENGTH
#endif
#define DEBUG_MAX_MESSAGE_LENGTH 128U

/* COMMUNICATION INTERFACE SELECTION */
#define DEFAULT_DEBUG_INTERFACE COMM_INTERFACE_UART
#define DEBUG_UART_BAUDRATE 115200U
#define DEBUG_SPI_CLOCK_HZ 1000000U
#define DEBUG_I2C_ADDRESS 0x50U

/* COMMUNICATION BEHAVIOR */
#ifdef COMM_TIMEOUT_MS
#undef COMM_TIMEOUT_MS
#endif
#define COMM_TIMEOUT_MS 100U

#ifdef COMM_RETRY_COUNT
#undef COMM_RETRY_COUNT
#endif
#define COMM_RETRY_COUNT 3U

#ifdef COMM_VERIFICATION_COUNT
#undef COMM_VERIFICATION_COUNT
#endif
#define COMM_VERIFICATION_COUNT 3U

#ifdef COMM_VERIFICATION_WINDOW_MS
#undef COMM_VERIFICATION_WINDOW_MS
#endif
#define COMM_VERIFICATION_WINDOW_MS 50U

/* APPLICATION-SPECIFIC PARAMETERS */
#define APP_INIT_TIMEOUT_MS 5000U
#define APP_PROCESSING_TIMEOUT_MS 3000U
#define APP_CALIBRATION_TIMEOUT_MS 5000U
#define APP_DIAGNOSTICS_TIMEOUT_MS 2000U
#define APP_RECOVERY_TIMEOUT_MS 2000U

/* FEATURE ENABLE/DISABLE FLAGS */
#define FEATURE_WATCHDOG_ENABLED 1U
#define FEATURE_LOW_POWER_ENABLED 0U
#define FEATURE_STATISTICS_ENABLED 0U
#define FEATURE_ASSERT_ENABLED 1U

/* HARDWARE-SPECIFIC DEFINITIONS */
#if defined(HARDWARE_PLATFORM)
#define SYSTEM_CLOCK_HZ 168000000U
#define FLASH_SIZE_KB 1024U
#define RAM_SIZE_KB 192U
#else
#define SYSTEM_CLOCK_HZ 100000000U
#define FLASH_SIZE_KB 512U
#define RAM_SIZE_KB 128U
#endif

/* VALIDATION CHECKS */
#if (SM_TASK_PERIOD_MS == 0)
#error "SM_TASK_PERIOD_MS cannot be zero"
#endif

#if (ERROR_MAX_RECOVERY_ATTEMPTS == 0)
#warning "ERROR_MAX_RECOVERY_ATTEMPTS is zero - no recovery will be attempted"
#endif

#if (DEBUG_MAX_MESSAGE_LENGTH < 32)
#warning "DEBUG_MAX_MESSAGE_LENGTH is very small - messages may be truncated"
#define PRINT_CONFIG_SUMMARY()
  do {
    Debug_SendMessage(DEBUG_MSG_INIT, "=== Configuration Summary ===");                      
    Debug_SendMessage(DEBUG_MSG_INIT, "Project: %s v%s", PROJECT_NAME, PROJECT_VERSION);    
    Debug_SendMessage(DEBUG_MSG_INIT, "Platform: %s", HARDWARE_PLATFORM);                    
    Debug_SendMessage(DEBUG_MSG_INIT, "Task Period: %u ms", SM_TASK_PERIOD_MS);              
    Debug_SendMessage(DEBUG_MSG_INIT, "Error Recovery Attempts: %u", ERROR_MAX_RECOVERY_ATTEMPTS);
    Debug_SendMessage(DEBUG_MSG_INIT, "Debug: Init=%d Runtime=%d Periodic=%d", DEBUG_ENABLE_INIT_MESSAGES, DEBUG_ENABLE_RUNTIME_MESSAGES, DEBUG_ENABLE_PERIODIC_MESSAGES); \
    } while (0)

#endif
#endif

/* CONFIGURATION SUMMARY MACRO */
/* CONFIGURATION SUMMARY MACRO */

#endif