"""Graph rebuild entry point.

CLAUDE.md contract:

    python3 -c "from graphify.watch import _rebuild_code; \
                from pathlib import Path; _rebuild_code(Path('.'))"

Also runnable as `python3 -m graphify.watch` from the repo root.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from .analyze import Graph, build_graph

OUT_DIR = "graphify-out"
GOD_NODE_COUNT = 12


def _write_report(root: Path, g: Graph) -> None:
    out = root / OUT_DIR
    out.mkdir(exist_ok=True)

    by_community: dict[str, list[str]] = defaultdict(list)
    for rel in g.files:
        by_community[g.community_of(rel)].append(rel)

    # Community edge structure: internal vs cross-community call edges
    comm_internal: dict[str, int] = defaultdict(int)
    cross: dict[tuple[str, str], int] = defaultdict(int)
    for fn in g.functions.values():
        src = g.community_of(fn.file)
        for callee_key in fn.calls:
            dst = g.community_of(g.functions[callee_key].file)
            if src == dst:
                comm_internal[src] += 1
            else:
                cross[(src, dst)] += 1

    god = sorted(
        g.functions.values(), key=lambda f: (-f.degree, f.name)
    )[:GOD_NODE_COUNT]

    total_edges = sum(len(f.calls) for f in g.functions.values())

    lines: list[str] = []
    lines.append("# Graph Report")
    lines.append("")
    lines.append("Generated by the repo-local `graphify` package "
                 "(`python3 -m graphify.watch`). Regenerate after code "
                 "changes; do not edit by hand.")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Files scanned: **{len(g.files)}**")
    lines.append(f"- Functions (definitions with bodies): "
                 f"**{len(g.functions)}**")
    lines.append(f"- Call edges: **{total_edges}**")
    lines.append(f"- Communities: **{len(by_community)}**")
    lines.append("")
    lines.append("## God nodes (highest call-graph degree)")
    lines.append("")
    lines.append("| Function | File | Line | In | Out | Degree |")
    lines.append("|---|---|---:|---:|---:|---:|")
    for f in god:
        lines.append(
            f"| `{f.name}` | `{f.file}` | {f.line} "
            f"| {len(f.callers)} | {len(f.calls)} | {f.degree} |"
        )
    lines.append("")
    lines.append("## Community structure")
    lines.append("")
    for comm in sorted(by_community):
        members = by_community[comm]
        fn_count = sum(1 for f in g.functions.values()
                       if g.community_of(f.file) == comm)
        lines.append(f"### {comm}")
        lines.append("")
        lines.append(f"- Files: {len(members)}, functions: {fn_count}, "
                     f"internal call edges: {comm_internal.get(comm, 0)}")
        outgoing = sorted(
            (dst, n) for (src, dst), n in cross.items() if src == comm
        )
        if outgoing:
            arrow = ", ".join(f"{dst} ({n})" for dst, n in outgoing)
            lines.append(f"- Calls into: {arrow}")
        for rel in members:
            lines.append(f"  - `{rel}`")
        lines.append("")

    (out / "GRAPH_REPORT.md").write_text("\n".join(lines) + "\n",
                                         encoding="utf-8")


def _write_wiki(root: Path, g: Graph) -> None:
    wiki = root / OUT_DIR / "wiki"
    wiki.mkdir(parents=True, exist_ok=True)

    by_file: dict[str, list] = defaultdict(list)
    for fn in g.functions.values():
        by_file[fn.file].append(fn)

    lines: list[str] = []
    lines.append("# Codebase Wiki")
    lines.append("")
    lines.append("Topic-grouped navigation generated by `graphify`. "
                 "Symbols are function definitions; line numbers refer to "
                 "the file at generation time.")
    lines.append("")

    by_community: dict[str, list[str]] = defaultdict(list)
    for rel in g.files:
        by_community[g.community_of(rel)].append(rel)

    order = [
        "Public API (headers)", "Core engine", "Platform / HAL",
        "App glue", "Configuration", "Examples", "Tests", "Other",
    ]
    for comm in order:
        if comm not in by_community:
            continue
        lines.append(f"## {comm}")
        lines.append("")
        for rel in by_community[comm]:
            fns = sorted(by_file.get(rel, []), key=lambda f: f.line)
            inc = g.includes.get(rel, [])
            lines.append(f"### `{rel}`")
            if inc:
                lines.append(f"- Includes: {', '.join(f'`{i}`' for i in inc)}")
            if fns:
                sym = ", ".join(f"`{f.name}`:{f.line}" for f in fns)
                lines.append(f"- Defines: {sym}")
            lines.append("")

    (wiki / "index.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _rebuild_code(root: Path) -> None:
    """Rebuild graphify-out/ for the repository at `root`."""
    root = root.resolve()
    g = build_graph(root)
    _write_report(root, g)
    _write_wiki(root, g)
    print(f"graphify: {len(g.functions)} functions, "
          f"{sum(len(f.calls) for f in g.functions.values())} call edges "
          f"-> {OUT_DIR}/")


if __name__ == "__main__":
    _rebuild_code(Path("."))
