/**
 * @file stm32_platform_stub.c
 * @brief STM32 HAL platform implementation for State Machine Framework v4.1
 * @version 4.1.0
 * @date 2026-04-19
 *
 * @copyright Copyright (c) 2025-2026
 *
 * REFERENCE IMPLEMENTATION -- NOT PRODUCTION-READY
 *
 * This file demonstrates how to implement all sm_platform.h HAL functions
 * for an STM32 target using the STM32 HAL drivers. It is provided as a
 * starting point for porting the framework to real hardware.
 *
 * To use:
 *   1. Copy this file into your project's source tree.
 *   2. Uncomment the appropriate STM32 HAL include for your target family.
 *   3. Adapt peripheral handles (huart2, hiwdg) to match your CubeMX config.
 *   4. Adjust NVS flash sector/page addresses for your specific MCU.
 *   5. Add this file to your build (CMake, Makefile, or IDE project).
 *   6. Do NOT link sm_platform_weak.c -- this file provides strong overrides.
 *
 * This file is NOT compiled by the project's CMake build system. It exists
 * solely as a reference for embedded integrators.
 *
 * Assumptions:
 *   - SystemCoreClock and HAL_Init() are configured by your startup code.
 *   - USART2 is used for debug output (common on Nucleo boards).
 *   - IWDG (Independent Watchdog) is used for the watchdog subsystem.
 *   - Internal flash is used for NVS (EEPROM emulation pattern).
 *   - SystemClock_Config() is user-defined (CubeMX generates this).
 */

#include "sm_framework/sm_platform.h"

/* ============================================================================
 * STM32 HAL INCLUDES
 *
 * Uncomment the appropriate header for your target family. Only one should
 * be active. These headers pull in CMSIS core (core_cm4.h, etc.) which
 * provides __disable_irq(), __enable_irq(), __BKPT(), NVIC_SystemReset().
 * ========================================================================= */

/* #include "stm32f0xx_hal.h" */
/* #include "stm32f1xx_hal.h" */
/* #include "stm32f3xx_hal.h" */
/* #include "stm32f4xx_hal.h" */
/* #include "stm32f7xx_hal.h" */
/* #include "stm32g0xx_hal.h" */
/* #include "stm32g4xx_hal.h" */
/* #include "stm32h7xx_hal.h" */
/* #include "stm32l4xx_hal.h" */
/* #include "stm32u5xx_hal.h" */

/* ============================================================================
 * FORWARD DECLARATIONS
 *
 * These are typically generated by CubeMX or defined in your main.c.
 * ========================================================================= */

/* extern UART_HandleTypeDef huart2;  -- debug UART handle */
/* extern IWDG_HandleTypeDef hiwdg;   -- independent watchdog handle */
/* extern void SystemClock_Config(void);  -- clock restore after STOP mode */

/* ============================================================================
 * NVS CONFIGURATION
 *
 * Adjust these for your specific STM32 variant. The values below are typical
 * for STM32F4 (dual-bank flash with 128KB sectors at the end).
 * ========================================================================= */

/* Flash sector used for NVS emulation (last sector, least-used) */
/* #define NVS_FLASH_SECTOR       FLASH_SECTOR_11 */
/* #define NVS_FLASH_BASE_ADDR    ((uint32_t)0x080E0000) */
/* #define NVS_FLASH_SIZE         ((uint32_t)0x20000)  -- 128KB */
/* #define NVS_MAX_ENTRIES        256 */

/* NVS entry layout: [uint16_t key][uint16_t len][data...] aligned to 32-bit */
/* typedef struct {             */
/*     uint16_t key;            */
/*     uint16_t len;            */
/*     uint8_t  data[];         */
/* } NVS_Entry_t;               */

/* ============================================================================
 * UART OUTPUT CONFIGURATION
 * ========================================================================= */

#define UART_TX_TIMEOUT_MS   100U   /* HAL_UART_Transmit timeout */

/* ============================================================================
 * TIMING
 * ========================================================================= */

/**
 * @brief Get current system time from SysTick via HAL
 *
 * HAL_GetTick() returns milliseconds since HAL_Init(). Driven by SysTick
 * interrupt (1 kHz default). Wraps at ~49.7 days (2^32 ms).
 */
uint32_t SM_Platform_GetTimeMs(void)
{
    /* return HAL_GetTick(); */
    return 0U;  /* Placeholder -- uncomment HAL_GetTick() above */
}

/**
 * @brief Simulation tick -- no-op on real hardware
 *
 * SysTick drives time on STM32. This function exists only to satisfy the
 * HAL interface. On real hardware it does nothing.
 */
void SM_Platform_SimTick(void)
{
    /* No-op: real hardware uses SysTick, not manual tick advancement */
}

/**
 * @brief Check if timeout has elapsed with 32-bit wraparound safety
 *
 * Uses unsigned subtraction which handles the 32-bit counter wraparound
 * correctly (works as long as the timeout is less than ~49.7 days).
 */
bool SM_Platform_IsTimeout(uint32_t start, uint32_t timeout_ms)
{
    uint32_t now = SM_Platform_GetTimeMs();

    /* Unsigned subtraction handles wraparound:
     * e.g., now=5, start=0xFFFFFFFE -> (5 - 0xFFFFFFFE) = 7 */
    return (now - start) >= timeout_ms;
}

/* ============================================================================
 * CRITICAL SECTIONS
 *
 * Bare-metal nesting-aware implementation using CMSIS __disable_irq() and
 * __enable_irq(). Interrupts are only re-enabled when nesting returns to 0.
 *
 * Important: __disable_irq() sets PRIMASK, which masks all interrupts
 * except NMI and HardFault. For FreeRTOS-based systems, use
 * taskENTER_CRITICAL() / taskEXIT_CRITICAL() instead.
 * ========================================================================= */

/** Nesting counter for critical sections. Interrupts disabled when > 0. */
static volatile uint32_t s_critical_nesting = 0U;

void SM_Platform_EnterCritical(void)
{
    /* __disable_irq(); */  /* Uncomment for real hardware */

    s_critical_nesting++;
}

void SM_Platform_ExitCritical(void)
{
    if (s_critical_nesting > 0U) {
        s_critical_nesting--;
    }

    if (s_critical_nesting == 0U) {
        /* __enable_irq(); */  /* Uncomment for real hardware */
    }
}

uint32_t SM_Platform_GetCriticalNesting(void)
{
    return s_critical_nesting;
}

/* ============================================================================
 * OUTPUT (UART debug interface)
 *
 * Uses USART2 which is common on ST Nucleo boards (connected to ST-Link
 * virtual COM port). Adapt the handle and init code to match your CubeMX
 * configuration.
 * ========================================================================= */

/**
 * @brief Initialize debug UART output
 *
 * @param interface  Interface ID (0 = USART2 debug port)
 * @return true if initialization succeeded
 *
 * In a CubeMX project, UART init is typically done in MX_USART2_UART_Init()
 * called from main(). This function can either call that directly or simply
 * verify the handle is ready.
 */
bool SM_Platform_OutputInit(uint8_t interface)
{
    if (interface != 0U) {
        return false;  /* Only interface 0 (USART2) supported */
    }

    /*
     * Typical USART2 configuration (115200 8N1):
     *
     * huart2.Instance          = USART2;
     * huart2.Init.BaudRate     = 115200;
     * huart2.Init.WordLength   = UART_WORDLENGTH_8B;
     * huart2.Init.StopBits     = UART_STOPBITS_1;
     * huart2.Init.Parity       = UART_PARITY_NONE;
     * huart2.Init.Mode         = UART_MODE_TX_RX;
     * huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
     * huart2.Init.OverSampling = UART_OVERSAMPLING_16;
     *
     * if (HAL_UART_Init(&huart2) != HAL_OK) {
     *     return false;
     * }
     */

    return true;  /* Placeholder -- uncomment HAL_UART_Init above */
}

/**
 * @brief Send data over debug UART
 *
 * Blocking transmit with timeout. For production systems, consider DMA
 * or interrupt-driven TX to avoid blocking the state machine.
 *
 * @param data  Pointer to data buffer
 * @param len   Number of bytes to send
 * @return Number of bytes actually sent (len on success, 0 on failure)
 */
uint32_t SM_Platform_OutputSend(const uint8_t *data, uint32_t len)
{
    if (data == NULL || len == 0U) {
        return 0U;
    }

    /*
     * HAL_StatusTypeDef status;
     * status = HAL_UART_Transmit(&huart2, (uint8_t *)data, (uint16_t)len,
     *                            UART_TX_TIMEOUT_MS);
     * return (status == HAL_OK) ? len : 0U;
     */

    (void)data;
    return len;  /* Placeholder -- uncomment HAL_UART_Transmit above */
}

/* ============================================================================
 * WATCHDOG (IWDG -- Independent Watchdog)
 *
 * The STM32 IWDG is clocked by the LSI oscillator (~32 kHz typical, but
 * can vary 17-47 kHz depending on part). Once started, the IWDG cannot be
 * stopped -- only a system reset disables it.
 *
 * Timeout calculation:
 *   timeout_ms = (prescaler * reload) / LSI_freq_kHz
 *   reload = (timeout_ms * LSI_freq_kHz) / prescaler
 *
 * With prescaler=64 and LSI=32kHz: reload = timeout_ms * 32 / 64 = timeout_ms / 2
 * Max reload = 0xFFF (4095), so max timeout ~= 8190 ms with prescaler=64.
 * ========================================================================= */

/**
 * @brief Kick (refresh) the independent watchdog
 *
 * Must be called periodically before the watchdog counter expires.
 */
void SM_Platform_WatchdogKick(void)
{
    /* HAL_IWDG_Refresh(&hiwdg); */
}

/**
 * @brief Start the independent watchdog with the specified timeout
 *
 * @param timeout_ms  Desired timeout in milliseconds
 *
 * Selects prescaler and reload to best approximate the requested timeout.
 * The IWDG uses the LSI oscillator (~32 kHz), so exact millisecond accuracy
 * is not guaranteed.
 */
void SM_Platform_WatchdogStart(uint32_t timeout_ms)
{
    (void)timeout_ms;

    /*
     * Prescaler selection for ~32 kHz LSI:
     *   PSC_4:   max ~512 ms
     *   PSC_8:   max ~1024 ms
     *   PSC_16:  max ~2048 ms
     *   PSC_32:  max ~4096 ms
     *   PSC_64:  max ~8192 ms
     *   PSC_128: max ~16384 ms
     *   PSC_256: max ~32768 ms
     *
     * Example for timeout_ms with prescaler 64:
     *   uint32_t reload = (timeout_ms * 32U) / 64U;  -- LSI ~32kHz
     *   if (reload > 0xFFFU) { reload = 0xFFFU; }
     *   if (reload == 0U) { reload = 1U; }
     *
     *   hiwdg.Instance       = IWDG;
     *   hiwdg.Init.Prescaler = IWDG_PRESCALER_64;
     *   hiwdg.Init.Reload    = reload;
     *   hiwdg.Init.Window    = IWDG_WINDOW_DISABLE;  -- no window mode
     *
     *   if (HAL_IWDG_Init(&hiwdg) != HAL_OK) {
     *       -- Handle error: IWDG init failed
     *   }
     */
}

/**
 * @brief Stop the independent watchdog
 *
 * WARNING: On all STM32 families, the IWDG cannot be stopped once started.
 * This is a hardware limitation -- the IWDG is clocked by the independent
 * LSI oscillator and has no stop mechanism. The only way to disable it is
 * via a system reset.
 *
 * This function is intentionally a no-op. Applications that need to
 * "pause" watchdog behavior should extend the timeout or ensure
 * SM_Platform_WatchdogKick() is called frequently enough.
 */
void SM_Platform_WatchdogStop(void)
{
    /*
     * IWDG cannot be stopped once started on STM32.
     * This is a hardware limitation of the independent watchdog.
     *
     * Alternatives:
     *   - Use WWDG (Window Watchdog) if your application needs stop capability
     *     (WWDG can be disabled via RCC clock gate, though this is not standard)
     *   - Set a very long timeout and kick frequently
     *   - Use the option bytes to disable IWDG hardware start on some parts
     */
}

/* ============================================================================
 * SLEEP MODES
 *
 * STM32 low-power modes (Cortex-M typical):
 *
 *   SLEEP:   CPU clock stopped, peripherals running, all SRAM retained.
 *            Wake: any interrupt. Resume is immediate.
 *
 *   STOP:    All clocks stopped except LSI/LSE. SRAM and register contents
 *            retained. Wake: EXTI line, RTC alarm, UART, etc.
 *            After wake, HSI is selected as system clock -- must reconfigure
 *            PLL/HSE via SystemClock_Config().
 *
 *   STANDBY: 1.2V domain powered off. SRAM lost (except backup SRAM on some
 *            parts). Only backup registers + RTC retained. Wake: WKUP pin,
 *            RTC alarm, NRST. Wakes through reset vector.
 * ========================================================================= */

/**
 * @brief Enter a low-power sleep mode
 *
 * @param mode  Sleep mode to enter
 */
void SM_Platform_EnterSleep(SM_SleepMode_t mode)
{
    switch (mode) {
    case SM_SLEEP_LIGHT:
        /*
         * SLEEP mode: CPU halted, peripherals active, fast wake on any IRQ.
         *
         * HAL_PWR_EnterSLEEPMode(PWR_MAINREGULATOR_ON, PWR_SLEEPENTRY_WFI);
         */
        break;

    case SM_SLEEP_DEEP:
        /*
         * STOP mode: all oscillators stopped, SRAM retained, slow wake.
         * After wake, clocks must be reconfigured.
         *
         * HAL_PWR_EnterSTOPMode(PWR_LOWPOWERREGULATOR_ON, PWR_STOPENTRY_WFI);
         */
        break;

    case SM_SLEEP_STANDBY:
        /*
         * STANDBY mode: near-off, wake via WKUP pin or RTC only.
         * All SRAM content is lost. Device resets on wake.
         *
         * -- Enable wakeup source before entering standby:
         * HAL_PWR_EnableWakeUpPin(PWR_WAKEUP_PIN1);
         *
         * HAL_PWR_EnterSTANDBYMode();
         * -- Execution does not resume here; device resets on wake.
         */
        break;

    default:
        /* Unknown mode: do nothing */
        break;
    }
}

/**
 * @brief Restore clocks and peripherals after waking from low-power mode
 *
 * After STOP mode, the STM32 runs from HSI (typically 16 MHz). This function
 * must reconfigure the PLL, restore the system clock to the desired frequency,
 * and re-initialize any peripherals that lost state.
 *
 * After STANDBY mode, the MCU resets through the reset vector, so this
 * function is not called -- normal init handles everything.
 */
void SM_Platform_ExitSleep(void)
{
    /*
     * Restore system clock after STOP mode:
     *
     * SystemClock_Config();  -- re-init PLL/HSE to full speed
     *
     * Re-initialize peripherals that may have lost state:
     *
     * HAL_UART_Init(&huart2);  -- restore debug UART
     *
     * If using DMA, re-enable DMA streams/channels as needed.
     * SysTick is automatically restored by HAL_Init() during
     * SystemClock_Config() on most CubeMX-generated projects.
     */
}

/* ============================================================================
 * NON-VOLATILE STORAGE (Flash EEPROM Emulation)
 *
 * This is a simplified pattern. For production use, consider:
 *   - ST's X-CUBE-EEPROM middleware (AN4894 / AN3969)
 *   - Dual-page wear-leveling scheme
 *   - CRC or checksum validation on stored data
 *   - Proper flash page/sector erase management
 *
 * The pattern below writes key-value pairs sequentially into a flash sector.
 * Reads scan from the beginning and return the last matching key. This is
 * intentionally simple -- a real implementation needs erase management,
 * page compaction, and write validation.
 *
 * IMPORTANT: Flash write granularity varies by STM32 family:
 *   - STM32F4: 8/16/32-bit or word (32-bit) depending on VDD
 *   - STM32H7: flash word = 256 bits (32 bytes) -- must write full flash words
 *   - STM32G0/G4: double-word (64-bit) program granularity
 *   Adapt HAL_FLASH_Program() typeProgram argument accordingly.
 * ========================================================================= */

/**
 * @brief Write data to non-volatile storage (flash emulation)
 *
 * @param key   Application-defined key (0-65535)
 * @param data  Pointer to data to write
 * @param len   Length in bytes
 * @return true if write succeeded
 */
bool SM_Platform_NVS_Write(uint16_t key, const void *data, uint16_t len)
{
    if (data == NULL || len == 0U) {
        return false;
    }

    (void)key;

    /*
     * Simplified flash write pattern:
     *
     * HAL_StatusTypeDef status;
     *
     * -- Unlock flash for programming
     * status = HAL_FLASH_Unlock();
     * if (status != HAL_OK) { return false; }
     *
     * -- Erase sector if needed (track via a page-full flag or header)
     * -- FLASH_EraseInitTypeDef erase;
     * -- erase.TypeErase   = FLASH_TYPEERASE_SECTORS;
     * -- erase.Sector      = NVS_FLASH_SECTOR;
     * -- erase.NbSectors   = 1;
     * -- erase.VoltageRange = FLASH_VOLTAGE_RANGE_3;  -- 2.7-3.6V
     * -- uint32_t sector_error = 0;
     * -- HAL_FLASHEx_Erase(&erase, &sector_error);
     *
     * -- Write header: key (16-bit) + len (16-bit) = 32-bit word
     * uint32_t header = ((uint32_t)len << 16U) | (uint32_t)key;
     * status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD,
     *                            write_address, header);
     * if (status != HAL_OK) { HAL_FLASH_Lock(); return false; }
     * write_address += 4U;
     *
     * -- Write data word-by-word (pad last word if needed)
     * const uint8_t *src = (const uint8_t *)data;
     * for (uint16_t i = 0U; i < len; i += 4U) {
     *     uint32_t word = 0xFFFFFFFFU;
     *     for (uint16_t b = 0; b < 4U && (i + b) < len; b++) {
     *         word &= ~((uint32_t)0xFF << (b * 8U));
     *         word |= (uint32_t)src[i + b] << (b * 8U);
     *     }
     *     status = HAL_FLASH_Program(FLASH_TYPEPROGRAM_WORD,
     *                                write_address, word);
     *     if (status != HAL_OK) { HAL_FLASH_Lock(); return false; }
     *     write_address += 4U;
     * }
     *
     * HAL_FLASH_Lock();
     * return true;
     */

    return false;  /* Placeholder -- uncomment flash logic above */
}

/**
 * @brief Read data from non-volatile storage (flash emulation)
 *
 * @param key   Application-defined key (0-65535)
 * @param data  Pointer to buffer for read data
 * @param len   Length in bytes (must match the length used during write)
 * @return true if read succeeded and key was found
 */
bool SM_Platform_NVS_Read(uint16_t key, void *data, uint16_t len)
{
    if (data == NULL || len == 0U) {
        return false;
    }

    (void)key;

    /*
     * Simplified flash read pattern -- scan entries sequentially:
     *
     * uint32_t addr = NVS_FLASH_BASE_ADDR;
     * uint32_t end  = NVS_FLASH_BASE_ADDR + NVS_FLASH_SIZE;
     * const uint8_t *found = NULL;
     *
     * while (addr < end) {
     *     uint32_t header = *(volatile uint32_t *)addr;
     *
     *     -- Erased flash reads as 0xFFFFFFFF
     *     if (header == 0xFFFFFFFFU) { break; }
     *
     *     uint16_t entry_key = (uint16_t)(header & 0xFFFFU);
     *     uint16_t entry_len = (uint16_t)(header >> 16U);
     *     addr += 4U;
     *
     *     if (entry_key == key && entry_len == len) {
     *         found = (const uint8_t *)addr;
     *     }
     *
     *     -- Advance past data (word-aligned)
     *     addr += ((uint32_t)entry_len + 3U) & ~3U;
     * }
     *
     * if (found != NULL) {
     *     memcpy(data, found, len);
     *     return true;
     * }
     *
     * return false;
     */

    return false;  /* Placeholder -- uncomment flash logic above */
}

/* ============================================================================
 * RESET REASON
 *
 * The RCC_CSR register contains flags indicating the cause of the last reset.
 * Multiple flags can be set simultaneously (e.g., POR + BOR on initial
 * power-up). This implementation checks in priority order and clears the
 * flags after reading.
 *
 * Flag names may differ slightly between STM32 families. Common ones:
 *   RCC_FLAG_IWDGRST  -- Independent watchdog reset
 *   RCC_FLAG_SFTRST   -- Software reset (NVIC_SystemReset)
 *   RCC_FLAG_PINRST   -- NRST pin reset
 *   RCC_FLAG_BORRST   -- Brown-out reset
 *   RCC_FLAG_PORRST   -- Power-on reset (some families use RCC_FLAG_PWRRST)
 * ========================================================================= */

/**
 * @brief Determine the cause of the last system reset
 *
 * Reads RCC reset flags, maps to SM_ResetReason_t, and clears the flags
 * so the next reset produces a clean reading.
 *
 * @return Reset reason code
 */
SM_ResetReason_t SM_Platform_GetResetReason(void)
{
    SM_ResetReason_t reason = SM_RESET_UNKNOWN;

    /*
     * -- Check flags in priority order (most specific first)
     *
     * if (__HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST)) {
     *     reason = SM_RESET_WATCHDOG;
     * } else if (__HAL_RCC_GET_FLAG(RCC_FLAG_SFTRST)) {
     *     reason = SM_RESET_SOFTWARE;
     * } else if (__HAL_RCC_GET_FLAG(RCC_FLAG_BORRST)) {
     *     reason = SM_RESET_BROWNOUT;
     * } else if (__HAL_RCC_GET_FLAG(RCC_FLAG_PINRST)) {
     *     reason = SM_RESET_EXTERNAL;
     * } else if (__HAL_RCC_GET_FLAG(RCC_FLAG_PORRST)) {
     *     reason = SM_RESET_POR;
     * }
     *
     * -- Clear all reset flags so next reset is clean
     * __HAL_RCC_CLEAR_RESET_FLAGS();
     */

    return reason;
}

/* ============================================================================
 * PLATFORM CAPABILITY CHECK
 * ========================================================================= */

/**
 * @brief Report which HAL capabilities this platform supports
 *
 * STM32 provides all subsystems. NVS depends on whether the flash emulation
 * code above is enabled -- set to true if your application configures it.
 *
 * @param cap  Capability to query
 * @return true if the capability is available
 */
bool SM_Platform_HasCapability(SM_PlatformCap_t cap)
{
    switch (cap) {
    case SM_CAP_WATCHDOG:
        return true;   /* IWDG available on all STM32 */

    case SM_CAP_NVS:
        /*
         * Set to true if you have enabled the flash EEPROM emulation
         * above (NVS_Write / NVS_Read). Set to false if NVS is not
         * configured for your application.
         */
        return false;

    case SM_CAP_SLEEP:
        return true;   /* All STM32 support SLEEP/STOP/STANDBY */

    case SM_CAP_OUTPUT:
        return true;   /* UART debug output available */

    case SM_CAP_COUNT:  /* fall through */
    default:
        return false;
    }
}

/* ============================================================================
 * ASSERTIONS
 *
 * On debug builds, the assertion handler prints the module name and numeric
 * ID over UART, then hits a BKPT instruction so a connected debugger halts
 * at the failure site. If no debugger is attached, BKPT causes a HardFault
 * which falls through to NVIC_SystemReset() as a fallback.
 *
 * On release builds, you may want to log to NVS and reset immediately
 * without the UART print to minimize latency.
 * ========================================================================= */

/**
 * @brief Platform assertion handler -- print, break, and reset
 *
 * @param module  Module name string (from SM_DEFINE_MODULE)
 * @param id      Numeric assertion identifier
 */
void SM_Platform_Assert(const char *module, int id)
{
    /* Disable interrupts to prevent further execution */
    /* __disable_irq(); */

    /*
     * Print assertion info over debug UART:
     *
     * char buf[80];
     * int n = snprintf(buf, sizeof(buf),
     *                  "\r\n*** ASSERT: %s #%d ***\r\n",
     *                  module ? module : "?", id);
     * if (n > 0) {
     *     HAL_UART_Transmit(&huart2, (uint8_t *)buf, (uint16_t)n,
     *                       UART_TX_TIMEOUT_MS);
     * }
     */

    (void)module;
    (void)id;

    /*
     * Breakpoint: halts if debugger is attached.
     * If no debugger, this escalates to HardFault.
     *
     * __BKPT(0);
     */

    /*
     * Fallback: force a system reset via NVIC.
     * Reached if BKPT does not halt (no debugger) and HardFault
     * handler routes here, or if BKPT is removed in release builds.
     *
     * NVIC_SystemReset();
     */

    /* Should never reach here; infinite loop as last resort */
    while (1) {
        /* Trapped */
    }
}
